odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 50
sensor_timeout: 0.1

odom0: /lemure_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10
odom0_relative: false

imu0: /imu
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              true, true, true,
              true, true, true]
imu0_differential: false
imu0_queue_size: 10
imu0_relative: true
imu0_remove_gravitational_acceleration: true
